
project_id = "cdoyjgiyrfziejbrcvpx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry_limit = 3600
enable_anonymous_sign_ups = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.generateWorksheet]
verify_jwt = false

[functions.submitFeedback]
verify_jwt = false

[functions.track-user-event]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-export-payment]
verify_jwt = true

[functions.verify-export-payment]
verify_jwt = false

[functions.add-tokens]
verify_jwt = true
