
import { supabase } from '@/integrations/supabase/client';
import { FormData as WorksheetFormData } from '@/components/WorksheetForm';

// URLs for the Edge Functions
const GENERATE_WORKSHEET_URL = 'https://bvfrkzdlklyvnhlpleck.supabase.co/functions/v1/generateWorksheet';
const SUBMIT_FEEDBACK_URL = 'https://bvfrkzdlklyvnhlpleck.supabase.co/functions/v1/submitFeedback';

/**
 * Generates a worksheet using the Edge Function
 */
export async function generateWorksheet(prompt: WorksheetFormData, userId: string) {
  try {
    // Send the entire prompt object to the edge function
    console.log('Sending prompt to generateWorksheet function:', prompt);
    
    const response = await fetch(GENERATE_WORKSHEET_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: JSON.stringify(prompt), // Send the entire prompt object as JSON
        userId
      })
    });

    // Check for error responses
    if (!response.ok) {
      // Try to parse the error as JSON
      const errorData = await response.json().catch(() => null);
      
      if (errorData && errorData.error) {
        throw new Error(errorData.error);
      }
      
      // Handle specific status codes with fallback error messages
      if (response.status === 401) {
        throw new Error('Authentication failed: Invalid or missing OpenAI API key. Please check your API key.');
      }
      
      if (response.status === 429) {
        throw new Error('You have reached your daily limit for worksheet generation. Please try again tomorrow.');
      }
      
      // Generic error message if we couldn't parse a more specific one
      throw new Error(`Failed to generate worksheet (status ${response.status})`);
    }

    // Check content type to determine how to handle the response
    const contentType = response.headers.get('content-type');
    
    if (contentType && contentType.includes('application/json')) {
      // Handle JSON response (likely an error message)
      const data = await response.json();
      if (data.error) {
        throw new Error(data.error);
      }
      return data.html || '';
    }
    
    // Get the HTML content generated by OpenAI
    const htmlContent = await response.text();
    console.log('Received HTML content from edge function');
    
    return htmlContent;
  } catch (error) {
    console.error('Error generating worksheet:', error);
    throw error;
  }
}

/**
 * Submits feedback for a worksheet
 */
export async function submitWorksheetFeedback(worksheetId: string, rating: number, comment: string, userId: string) {
  try {
    console.log('Submitting feedback:', { worksheetId, rating, comment, userId });
    
    const { data, error } = await supabase
      .from('feedbacks')
      .insert({
        worksheet_id: worksheetId,
        rating: rating,
        comment: comment,
        user_id: userId
      });

    if (error) {
      console.error('Error submitting feedback directly to Supabase:', error);
      
      // Fallback to edge function if direct insert fails
      const response = await fetch(SUBMIT_FEEDBACK_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          worksheetId,
          rating,
          comment,
          userId
        })
      });

      if (!response.ok) {
        throw new Error(`Failed to submit feedback: ${await response.text()}`);
      }
      
      return await response.json();
    }
    
    return data;
  } catch (error) {
    console.error('Error submitting feedback:', error);
    throw error;
  }
}

/**
 * Tracks an event (view, download, etc.)
 */
export async function trackEvent(type: string, worksheetId: string, userId: string, metadata: any = {}) {
  try {
    const { error } = await supabase.from('events').insert({
      type,
      worksheet_id: worksheetId,
      user_id: userId,
      metadata
    });

    if (error) throw error;
  } catch (error) {
    console.error(`Error tracking ${type} event:`, error);
  }
}
