// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdoyjgiyrfziejbrcvpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkb3lqZ2l5cmZ6aWVqYnJjdnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTYzMDgsImV4cCI6MjA2NjA5MjMwOH0.ZLJPaIH9kVcU2dIxk7KOq6sg3OVkxfaMvO2KI6p--nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});